---
- name: Instalar HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Desplegar configuración de HAProxy desde el template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Reiniciar HAProxy

- name: Asegurar que HAProxy esté iniciado
  service:
    name: haproxy
    state: started
    enabled: yes

    