---
- name: "Hacer pull de la imagen: {{ app_image }}"
  docker_image:
    name: "{{ app_image }}"
    source: pull
    # force_source: yes

- name: "Desplegar contenedor: {{ app_name }}"
  docker_container:
    name: "{{ app_name }}"
    image: "{{ app_image }}"
    state: started
    restart_policy: always
    # Si la variable está vacía o no existe, Ansible ignora por completo este parámetro
    ports: "{{ [app_port_mapping] if app_port_mapping | default('') != '' else omit }}"
    env: "{{ app_env_vars | default({}) }}"