[proxy]
192.168.56.10

[frontend]
192.168.56.11

[backend_auth_users]
192.168.56.12

[backend_todos]
192.168.56.13

[data]
192.168.56.14

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key