---
- name: Preparar infraestructura base
  hosts: all
  become: true
  roles:
    - common

- name: Desplegar Persistencia y Lógica Pesada
  hosts: node_data
  become: true
  tasks:
    - name: Levantar Redis Queue
      include_role:
        name: app_deploy
      vars:
        app_name: "redis-queue"
        app_image: "redis:alpine"
        app_port_mapping: "6379:6379"

    - name: Levantar Zipkin (Trazabilidad)
      include_role:
        name: app_deploy
      vars:
        app_name: "zipkin-server"
        app_image: "openzipkin/zipkin:latest"
        app_port_mapping: "9411:9411"

    - name: Levantar Users API (Límite estricto de RAM)
      include_role:
        name: app_deploy
      vars:
        app_name: "users-api"
        app_image: "ghcr.io/andresbueno420/users-api:latest"
        app_port_mapping: "8083:8083"
        app_env_vars:
          JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m"
          ZIPKIN_URL: "http://192.168.56.11:9411/api/v2/spans"

    - name: Levantar Log Processor
      include_role:
        name: app_deploy
      vars:
        app_name: "log-processor"
        app_image: "ghcr.io/andresbueno420/log-message-processor:latest"
        app_port_mapping: "" 
        app_env_vars:
          REDIS_HOST: "192.168.56.11"
          REDIS_PORT: "6379"
          ZIPKIN_URL: "http://192.168.56.11:9411/api/v2/spans"

- name: Configurar Gateway y Front
  hosts: node_apps
  become: true
  tasks:
    - name: Desplegar HAProxy
      include_role:
        name: haproxy

    - name: Levantar Auth API
      include_role:
        name: app_deploy
      vars:
        app_name: "auth-api"
        app_image: "ghcr.io/andresbueno420/auth-api:latest"
        app_port_mapping: "8000:8000"
        app_env_vars:
          AUTH_API_PORT: "8000" 
          JWT_SECRET: "PRFT"
          USERS_API_ADDRESS: "http://192.168.56.11:8083"
          ZIPKIN_URL: "http://192.168.56.11:9411/api/v2/spans"

    - name: Levantar TODOs API
      include_role:
        name: app_deploy
      vars:
        app_name: "todos-api"
        app_image: "ghcr.io/andresbueno420/todos-api:latest"
        app_port_mapping: "8082:8082"
        app_env_vars:
          REDIS_HOST: "192.168.56.11"
          REDIS_PORT: "6379"
          ZIPKIN_URL: "http://192.168.56.11:9411/api/v2/spans"

    - name: Levantar Frontend Vue
      include_role:
        name: app_deploy
      vars:
        app_name: "frontend-app"
        app_image: "ghcr.io/andresbueno420/frontend:latest"
        app_port_mapping: "8080:8080"
        app_env_vars:
          AUTH_API_ADDRESS: "http://192.168.56.10:8000"
          TODOS_API_ADDRESS: "http://192.168.56.10:8082"
          ZIPKIN_URL: "http://192.168.56.11:9411/api/v2/spans"
